version: 2
updates: 
  # Enable version updates for nuget 
  - package-ecosystem: "nuget"
    directory: "source"
    # Check the nuget registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"